# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class S2tPostRequestAudio(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content=None):  # noqa: E501
        """S2tPostRequestAudio - a model defined in OpenAPI

        :param content: The content of this S2tPostRequestAudio.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'content': str
        }

        self.attribute_map = {
            'content': 'content'
        }

        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'S2tPostRequestAudio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _s2t_post_request_audio of this S2tPostRequestAudio.  # noqa: E501
        :rtype: S2tPostRequestAudio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self):
        """Gets the content of this S2tPostRequestAudio.


        :return: The content of this S2tPostRequestAudio.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this S2tPostRequestAudio.


        :param content: The content of this S2tPostRequestAudio.
        :type content: str
        """

        self._content = content
